from os import path

TESTS = {
    "ig_1d_singledisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 1,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
    },
    "ig_1d_multidisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 1,
        "discretizations": 10,
        "divisions": 1,
        "seed": 12345,
        "range": 0.5,
    },
    "ig_2d_singledisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
    },
    "ig_2d_multidisc": {
        "variables_count": 100,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 5,
        "divisions": 3,
        "seed": 12345,
        "range": 0.2,
    },
    "ig_3d_singledisc": {
        "variables_count": 70,
        "objects_count": 1000,
        "dimensions": 3,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
    },
    "ig_4d_singledisc": {
        "variables_count": 30,
        "objects_count": 1000,
        "dimensions": 4,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
    },
    "ig_5d_singledisc": {
        "variables_count": 15,
        "objects_count": 1000,
        "dimensions": 5,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
    },
    "tid_2d_singledisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
        "stat_mode": "VI",
    },
    "tid_2d_multidisc": {
        "variables_count": 100,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 5,
        "divisions": 3,
        "seed": 12345,
        "range": 0.2,
        "stat_mode": "VI",
    },
    "entropy_1d_singledisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 1,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
        "with_decision": False,
        "stat_mode": "H",
    },
    "entropy_1d_multidisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 1,
        "discretizations": 10,
        "divisions": 1,
        "seed": 12345,
        "range": 0.5,
        "with_decision": False,
        "stat_mode": "H",
    },
    "mutualinfo_2d_singledisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
        "with_decision": False,
    },
    "mutualinfo_2d_multidisc": {
        "variables_count": 100,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 5,
        "divisions": 3,
        "seed": 12345,
        "range": 0.2,
        "with_decision": False,
    },
    "vi_2d_singledisc": {
        "variables_count": 200,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 1,
        "divisions": 1,
        "seed": 12345,
        "range": 0.0,
        "with_decision": False,
        "stat_mode": "VI",
    },
    "vi_2d_multidisc": {
        "variables_count": 100,
        "objects_count": 1000,
        "dimensions": 2,
        "discretizations": 5,
        "divisions": 3,
        "seed": 12345,
        "range": 0.2,
        "with_decision": False,
        "stat_mode": "VI",
    },
}


_TEST_RESULTS_PATH = "test_results"


def get_results_path(name):
    return path.join(_TEST_RESULTS_PATH, name)
